package:
  name: decidim.electionguard
  version: 0.1.0
source:
  url: https://github.com/codegram/decidim.electionguard/raw/master/dist/decidim.electionguard-0.1.0.tar.gz
requirements:
  run:
  - electionguard
